# Generated by Django 4.2.6 on 2023-10-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ad",
            name="locations",
            field=models.ManyToManyField(
                choices=[
                    ("Karachi", "Karachi"),
                    ("Lahore", "Lahore"),
                    ("Multan", "Multan"),
                ],
                to="ads.location",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(
                choices=[
                    ("Karachi", "Karachi"),
                    ("Lahore", "Lahore"),
                    ("Multan", "Multan"),
                ],
                default="Karachi",
                max_length=100,
            ),
        ),
    ]
