# Generated by Django 4.2.6 on 2023-10-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0002_ad_is_blocked_alter_ad_locations_alter_location_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="locations",
            field=models.ManyToManyField(to="ads.location"),
        ),
    ]
