# Generated by Django 4.2.6 on 2023-10-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0005_remove_ad_is_blocked_ad_max_daily_visitors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="locations",
            field=models.CharField(
                choices=[
                    ("Karachi", "Karachi"),
                    ("Lahore", "Lahore"),
                    ("Multan", "Multan"),
                ],
                default="Karachi",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="max_daily_visitors",
            field=models.PositiveIntegerField(),
        ),
    ]
