# Generated by Django 4.2.6 on 2023-10-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0006_alter_ad_locations_alter_ad_max_daily_visitors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Karachi", "Karachi"),
                            ("Lahore", "Lahore"),
                            ("Multan", "Multan"),
                        ],
                        default="Karachi",
                        max_length=100,
                    ),
                ),
                ("max_daily_visitors", models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="ad",
            name="max_daily_visitors",
        ),
        migrations.RemoveField(
            model_name="ad",
            name="locations",
        ),
        migrations.AddField(
            model_name="ad",
            name="locations",
            field=models.ManyToManyField(
                choices=[
                    ("Karachi", "Karachi"),
                    ("Lahore", "Lahore"),
                    ("Multan", "Multan"),
                ],
                to="ads.location",
            ),
        ),
    ]
