# Generated by Django 4.2.6 on 2023-10-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0007_location_remove_ad_max_daily_visitors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="locations",
            field=models.ManyToManyField(to="ads.location"),
        ),
    ]
