# Generated by Django 4.2.6 on 2023-10-27 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0012_alter_ad_ad_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("visitor_count", models.PositiveIntegerField(default=0)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ads.location"
                    ),
                ),
            ],
        ),
    ]
