# Generated by Django 4.2.6 on 2023-10-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0015_uservisit"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="users_per_day",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
