# Generated by Django 4.2.6 on 2023-10-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0016_location_users_per_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileStored",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("content", models.TextField()),
            ],
        ),
    ]
