# Generated by Django 4.2.6 on 2023-10-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0017_filestored"),
    ]

    operations = [
        migrations.AddField(
            model_name="filestored",
            name="file",
            field=models.FileField(default="default_value_here", upload_to="files/"),
        ),
    ]
