# Generated by Django 4.2.6 on 2023-10-29 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0019_uservisit_view_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filestored",
            name="content",
        ),
        migrations.AlterField(
            model_name="createuser",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ads.location",
            ),
        ),
        migrations.DeleteModel(
            name="LocationVisitor",
        ),
    ]
