# Generated by Django 4.2.6 on 2023-10-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0020_remove_filestored_content_alter_createuser_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filestored",
            name="content",
            field=models.TextField(default="aa"),
        ),
    ]
