# Generated by Django 4.2.6 on 2023-10-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0021_filestored_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filestored",
            name="content",
            field=models.TextField(),
        ),
    ]
